namespace NWamp
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Net;
    using NWamp.Mapping;
    using NWamp.Transport;
    using NWamp.Protocol.Messages;
using System;

    /// <summary>
    /// Client-side WAMP protocol implementation. Derive from this class to create working 
    /// Websocket Application Message Protocol client-side listener based on choosen web sockets implementation.
    /// </summary>
    public abstract class WampClient : BaseWampProtocol
    {
        #region Fields & Properties
        
        /// <summary>
        /// Gets Web socket access interface used for communication. This provides an abstraction layer
        /// for specific web sockets implementations.
        /// </summary>
        public IWebSocket Socket { get; protected set; }

        /// <summary>
        /// List of current calls. Calls are made by client using RPC pattern. This collection
        /// has only thoose of them, which haven't finished yet and are specific for current client session.
        /// </summary>
        private readonly IList<string> calls;

        /// <summary>
        /// List of currently subscribed topics. Topics are used for Pub/Sub pattern.
        /// </summary>
        private readonly HashSet<string> topics;

        /// <summary>
        /// Gets List of prefixes defined by current client. Prefixes definies shortcuts
        /// in form of CURIE-URI pair mappings.
        /// </summary>
        public PrefixMap Prefixes { get; private set; }

        /// <summary>
        /// Gets Current client session identifier. This value is generated by server
        /// and returned in "Welcome" message frame, when web socket connection has been established.
        /// </summary>
        public string SessionId { get; protected set; }

        /// <summary>
        /// Gets value determining, if current client is connected using WAMP protocol.
        /// </summary>
        public bool IsConnected { get; protected set; }

        #endregion

        /// <summary>
        /// Creates new instance of <see cref="WampClient"/> class.
        /// </summary>
        /// <param name="socket">Interface used to access implementation-specific web socket library.</param>
        /// <param name="serializer">Custom JSON serializer.</param>
        public WampClient(IWebSocket socket) : this(socket, null, null)
        {
        }

        /// <summary>
        /// Creates new instance of <see cref="WampClient"/> class.
        /// </summary>
        /// <param name="socket">Interface used to access implementation-specific web socket library.</param>
        /// <param name="serializer">Custom JSON serialization method.</param>
        /// <param name="deserializer">Custom JSON deserialization method.</param>
        public WampClient(IWebSocket socket, Func<object, string> serializer, Func<string, object> deserializer)
            : base(serializer, deserializer)
        {
            this.Socket = socket;
            this.calls = new List<string>();
            this.topics = new HashSet<string>();
            this.Prefixes = new PrefixMap();
        }

        /// <summary>
        /// Connects to new WAMP listener, which is listening under provided url.
        /// </summary>
        /// <param name="uri"></param>
        public abstract void Connect(string uri);

        #region WAMP client actions

        /// <summary>
        /// Sets new CURIE->URI mapping between current client and connected WAMP server listener.
        /// </summary>
        /// <param name="curie">CURIE format prefix.</param>
        /// <param name="uri">Valid URI resource path.</param>
        public void Prefix(string curie, string uri)
        {
            var msg = new PrefixMessage(curie, uri);
            var json = this.SerializeMessage(msg);
            
            this.Socket.SendMessage(json);
        }

        /// <summary>
        /// Subscribes current WAMP client to target topic.
        /// </summary>
        public void Subscribe(string topicId)
        {
            var subMsg = new SubscribeMessage(topicId);
            var json = this.SerializeMessageFrame(subMsg.ToArray());
            this.Socket.SendMessage(json);

            this.topics.Add(topicId);
        }

        /// <summary>
        /// Unsubscribes current WAMP client from target topic.
        /// </summary>
        public void Unsubscribe(string topicId)
        {
            var subMsg = new UnsubscribeMessage(topicId);
            var json = this.SerializeMessage(subMsg);
            this.Socket.SendMessage(json);

            this.topics.Remove(topicId);
        }

        /// <summary>
        /// Publishes new event object on target topic id.
        /// </summary>
        /// <param name="topicId">Topic identifier.</param>
        /// <param name="evt">Event object published among all topic subscribers.</param>
        /// <param name="excludeMe">Should current client receive publish message?</param>
        public void PublishAll(string topicId, object evt, bool excludeMe = false)
        {
            this.Publish(topicId, evt, excludeMe, null, null);
        }

        /// <summary>
        /// Publishes new event object on target topic id.
        /// </summary>
        /// <param name="topicId">Topic identifier.</param>
        /// <param name="evt">Event object published among eligible subscribers.</param>
        /// <param name="eligibles">List of eligible receivers.</param>
        public void Publish(string topicId, object evt, IEnumerable<string> eligibles)
        {
            this.Publish(topicId, evt, null, eligibles, null);
        }

        /// <summary>
        /// Publishes new event object on target topic id.
        /// </summary>
        /// <param name="topicId">Topic identifier.</param>
        /// <param name="evt">
        /// Event object published among all topic subscribers, except the specified ones.
        /// </param>
        /// <param name="excludes">List of excluded topic subscribers.</param>
        public void PublishExcept(string topicId, object evt, IEnumerable<string> excludes)
        {
            this.Publish(topicId, evt, null, null, excludes);
        }

        /// <summary>
        /// Performs a RPC action call with specified parameters.
        /// </summary>
        public void Call(string procUri, params object[] args)
        {
            var callId = this.GenerateSessionKey(16);
            var msg = new CallMessage(callId, procUri, args);
            var json = this.SerializeMessage(msg);

            this.Socket.SendMessage(json);
            this.calls.Add(callId);
        }

        private void Publish(string topicId, object evt, bool? excludeMe, IEnumerable<string> eligibles, IEnumerable<string> excludes)
        {
            var msg = excludeMe.HasValue
                ? new PublishMessage(topicId, evt, excludeMe.Value)
                : new PublishMessage(topicId, evt, eligibles.ToList(), excludes.ToList());

            var json = this.SerializeMessage(msg);
            this.Socket.SendMessage(json);
        }

        #endregion

        #region Message receiving & responding

        /// <summary>
        /// Method invoked when new WAMP message has been received.
        /// </summary>
        protected bool OnMessageReceived(IWampMessage message)
        {
            var type = message.Type;
            switch (type)
            {
                case MessageTypes.Welcome:
                    OnWelcomeReceived((WelcomeMessage)message);
                    return true;

                case MessageTypes.CallResult:
                    OnCallResult((CallResultMessage)message);
                    return true;

                case MessageTypes.CallError:
                    OnCallError((CallErrorMessage)message);
                    return true;

                case MessageTypes.Event:
                    OnEvent((EventMessage)message);
                    return true;
            }
            return false;
        }

        /// <summary>
        /// Method invoked, when new <see cref="EventMessage"/> has been received.
        /// </summary>
        protected virtual void OnEvent(EventMessage eventMessage)
        {
            throw new System.NotImplementedException();
        }

        /// <summary>
        /// Method invoked, when new <see cref="CallErrorMessage"/> has been received.
        /// </summary>
        protected virtual void OnCallError(CallErrorMessage callErrorMessage)
        {
            throw new System.NotImplementedException();
        }

        /// <summary>
        /// Method invoked, when new <see cref="CallResultMessage"/> has been received.
        /// </summary>
        protected virtual void OnCallResult(CallResultMessage callResultMessage)
        {
            throw new System.NotImplementedException();
        }

        /// <summary>
        /// Method invoked when new WAMP welcome message has been received.
        /// </summary>
        /// <exception cref="ProtocolViolationException">
        /// Exception thrown when incompatibile WAMP version has been detected.
        /// </exception>
        protected virtual void OnWelcomeReceived(WelcomeMessage msg)
        {
            if (WampConfiguration.ProtocolVersion != msg.ProtocolVersion)
                throw new ProtocolViolationException(
                    string.Format("Incompatybile WAMP protocol versions. Currently accepted version is {0}, but WELCOME version is {1}",
                    WampConfiguration.ProtocolVersion,
                    msg.ProtocolVersion));

            this.SessionId = msg.SessionId;
            this.IsConnected = true;
        }

        #endregion
    }
}